# Generated by Django 5.1.3 on 2025-07-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(max_length=1000)),
                ('background_image_url', models.URLField(max_length=1000)),
                ('link', models.CharField(default='#', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('carousel', 'Carousel'), ('grid', 'Grid'), ('featured', 'Featured Content')], max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('content_selection_type', models.CharField(choices=[('manual', 'Manual Selection'), ('automatic', 'Automatic Selection')], default='manual', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('auto_genre', models.ForeignKey(blank=True, help_text='If automatic selection, content will be filtered by this genre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.genre')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.landingpage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.section')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('landing_page', 'section')},
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='sections',
            field=models.ManyToManyField(through='movies.LandingPageSection', to='movies.section'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(max_length=1000)),
                ('background_image_url', models.URLField(max_length=1000)),
                ('link', models.CharField(default='#', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seasons', models.PositiveIntegerField(default=1)),
                ('episodes_count', models.PositiveIntegerField(default=0)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(related_name='series', to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.section')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('section', 'content_type', 'object_id')},
            },
        ),
    ]
