# Generated by Django 5.1.3 on 2025-07-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryMovie',
            new_name='MovieInCategory',
        ),
    ]
